### ISSUE TITLE
Using a list of names per principal is limited to 1000 - but there will be more than that

### ISSUE THREAD

**Issue by Patotking12** [Trust-Machines/BNS-V2#47]
As stated by Hank having a list to keep track of the names owned by a principal is a bad idea, since we could reach the limit.
In cases:

- Owner is a contract

He suggested updating it to use a linked list approach [here](https://github.com/mechanismHQ/bns-x/blob/main/contracts/contracts/core/name-registry.clar#L435-L555) 

We need to update accordingly

**Comment by jcnelson** [comment]
You may want to re-think updating the imported names' renewal times altogether, since there can be an effectively unbounded number of names in a namespace when it is launched.  You'll only be able to update a (small) finite number of them in the namespace-launch contract-call.

IIRC back in the Blockstack days, we just computed the name's "registration" time as the maximum of the following:

* the name's import time (will be 0 if the name was never imported)
* the namespace launch time (always defined)
* the name's last-registered time (will be 0 for imported names, at first)

**Comment by Patotking12** [comment]
Ok looking into this
